### ISSUE TITLE
SparseNet depth_40_gr_12 validation error is 7.31% on cifar10

### ISSUE THREAD

**Issue by Sirius083** [Lyken17/SparseNet#7]
the tensorflow implementation on  SparseNet depth=40 growth_rate=12 (no bottleneck) on cifar10  best validation error is 7.31%
while the paper reported error is 5.47%
what reason could probably cause the difference?
(change nothing excepth for the training log directory)
tensorflow version 1.12
tensorpack version 0.9.1
python version 3.6.6

Looking forward to your reply

**Comment by Lyken17** [comment]
I think I know what is happening... This bug is related to certain CUDA and CUDNN version. Can you share your version?

**Comment by Sirius083** [comment]
thanks for your reply, my 
cuda version: 9.0
cudnn version: 7.0

**Comment by Sirius083** [comment]
I changed the model setting to depth_40_k_24 on cifar10, then the results (min-validation error is 0.566) is  almost same as presented in the paper :blush:

**Comment by Lyken17** [comment]
Happy to see you solve the problem. I will fix the typo and prepare an updated version.
